// Source: https://docs.netlify.com/frameworks/express/ 

[build]
  publish = "public"
  functions = "netlify/functions"

  [functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[[redirects]]
  from = "/server/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
